TRUNCATE TABLE ADQUIRENTES
INSERT INTO ADQUIRENTES
SELECT * FROM [BALCAO].LOJA.DBO.ADQUIRENTES


TRUNCATE TABLE BANDEIRAS
INSERT INTO BANDEIRAS
SELECT * FROM [BALCAO].LOJA.DBO.BANDEIRAS

TRUNCATE TABLE BIOMETRIAS
INSERT INTO BIOMETRIAS(BIOMETRIA, DATA_HORA, TIPO, CODIGO, STATUS, NITGEN_ISDB, VENDEDOR)
SELECT BIOMETRIA, DATA_HORA, TIPO, CODIGO, STATUS, NITGEN_ISDB, VENDEDOR FROM [BALCAO].LOJA.DBO.BIOMETRIAS


TRUNCATE TABLE CARTOES_FAMILIAS
INSERT INTO CARTOES_FAMILIAS
SELECT * FROM [BALCAO].LOJA.DBO.CARTOES_FAMILIAS


TRUNCATE TABLE CARTOES_GRUPOS
INSERT INTO CARTOES_GRUPOS
SELECT * FROM [BALCAO].LOJA.DBO.CARTOES_GRUPOS


TRUNCATE TABLE CARTOES_PRODUTOS
INSERT INTO CARTOES_PRODUTOS
SELECT * FROM [BALCAO].LOJA.DBO.CARTOES_PRODUTOS


TRUNCATE TABLE CARTOES_SECOES
INSERT INTO CARTOES_SECOES
SELECT * FROM [BALCAO].LOJA.DBO.CARTOES_SECOES


TRUNCATE TABLE CARTOES_SUBGRUPOS
INSERT INTO CARTOES_SUBGRUPOS
SELECT * FROM [BALCAO].LOJA.DBO.CARTOES_SUBGRUPOS


TRUNCATE TABLE CODIGOS_BANDEIRAS
INSERT INTO CODIGOS_BANDEIRAS
SELECT * FROM [BALCAO].LOJA.DBO.CODIGOS_BANDEIRAS


TRUNCATE TABLE CONVENIOS_GRUPOS
INSERT INTO CONVENIOS_GRUPOS
SELECT * FROM [BALCAO].LOJA.DBO.CONVENIOS_GRUPOS


TRUNCATE TABLE CONVENIOS_MARCAS
INSERT INTO CONVENIOS_MARCAS
SELECT * FROM [BALCAO].LOJA.DBO.CONVENIOS_MARCAS


TRUNCATE TABLE CONVENIOS_PRODUTOS
INSERT INTO CONVENIOS_PRODUTOS
SELECT * FROM [BALCAO].LOJA.DBO.CONVENIOS_PRODUTOS


TRUNCATE TABLE CONVENIOS_PROMOCIONAIS
INSERT INTO CONVENIOS_PROMOCIONAIS
SELECT * FROM [BALCAO].LOJA.DBO.CONVENIOS_PROMOCIONAIS


TRUNCATE TABLE CONVENIOS_PROMOCIONAIS_CLASSES
INSERT INTO CONVENIOS_PROMOCIONAIS_CLASSES
SELECT * FROM [BALCAO].LOJA.DBO.CONVENIOS_PROMOCIONAIS_CLASSES


TRUNCATE TABLE CONVENIOS_PROMOCIONAIS_GRUPOS
INSERT INTO CONVENIOS_PROMOCIONAIS_GRUPOS
SELECT * FROM [BALCAO].LOJA.DBO.CONVENIOS_PROMOCIONAIS_GRUPOS


TRUNCATE TABLE CONVENIOS_PROMOCIONAIS_MARCAS
INSERT INTO CONVENIOS_PROMOCIONAIS_MARCAS
SELECT * FROM [BALCAO].LOJA.DBO.CONVENIOS_PROMOCIONAIS_MARCAS


TRUNCATE TABLE CONVENIOS_PROMOCIONAIS_PRODUTOS
INSERT INTO CONVENIOS_PROMOCIONAIS_PRODUTOS
SELECT * FROM [BALCAO].LOJA.DBO.CONVENIOS_PROMOCIONAIS_PRODUTOS


TRUNCATE TABLE CONVENIOS_PROMOCIONAIS_SECOES
INSERT INTO CONVENIOS_PROMOCIONAIS_SECOES
SELECT * FROM [BALCAO].LOJA.DBO.CONVENIOS_PROMOCIONAIS_SECOES


TRUNCATE TABLE CONVENIOS_PROMOCIONAIS_SUBGRUPOS
INSERT INTO CONVENIOS_PROMOCIONAIS_SUBGRUPOS
SELECT * FROM [BALCAO].LOJA.DBO.CONVENIOS_PROMOCIONAIS_SUBGRUPOS


TRUNCATE TABLE CONVENIOS_SECOES
INSERT INTO CONVENIOS_SECOES
SELECT * FROM [BALCAO].LOJA.DBO.CONVENIOS_SECOES


TRUNCATE TABLE CONVENIOS_SUBGRUPOS
INSERT INTO CONVENIOS_SUBGRUPOS
SELECT * FROM [BALCAO].LOJA.DBO.CONVENIOS_SUBGRUPOS


TRUNCATE TABLE CORRELATOS
INSERT INTO CORRELATOS
SELECT * FROM [BALCAO].LOJA.DBO.CORRELATOS


TRUNCATE TABLE CR_PRESCRITOR
INSERT INTO CR_PRESCRITOR
SELECT * FROM [BALCAO].LOJA.DBO.CR_PRESCRITOR


TRUNCATE TABLE CUSTO
INSERT INTO CUSTO
SELECT * FROM [BALCAO].LOJA.DBO.CUSTO


TRUNCATE TABLE DESCONTOS_PROGRESSIVOS
INSERT INTO DESCONTOS_PROGRESSIVOS
SELECT * FROM [BALCAO].LOJA.DBO.DESCONTOS_PROGRESSIVOS


TRUNCATE TABLE DESCONTOS_PROGRESSIVOS_PROMOCOES
INSERT INTO DESCONTOS_PROGRESSIVOS_PROMOCOES
SELECT * FROM [BALCAO].LOJA.DBO.DESCONTOS_PROGRESSIVOS_PROMOCOES


TRUNCATE TABLE EAN
INSERT INTO EAN
SELECT * FROM [BALCAO].LOJA.DBO.EAN


TRUNCATE TABLE ESTADOS
INSERT INTO ESTADOS
SELECT * FROM [BALCAO].LOJA.DBO.ESTADOS


TRUNCATE TABLE FPOPULAR_PERIODOS_DISPENSACOES
INSERT INTO FPOPULAR_PERIODOS_DISPENSACOES
SELECT * FROM [BALCAO].LOJA.DBO.FPOPULAR_PERIODOS_DISPENSACOES


TRUNCATE TABLE MAQUINAS_POS
INSERT INTO MAQUINAS_POS
SELECT * FROM [BALCAO].LOJA.DBO.MAQUINAS_POS


TRUNCATE TABLE MEDICOS
INSERT INTO MEDICOS
SELECT * FROM [BALCAO].LOJA.DBO.MEDICOS


TRUNCATE TABLE MOEDAS
INSERT INTO MOEDAS
SELECT * FROM [BALCAO].LOJA.DBO.MOEDAS


TRUNCATE TABLE MOEDAS_CONVERSOES
INSERT INTO MOEDAS_CONVERSOES
SELECT * FROM [BALCAO].LOJA.DBO.MOEDAS_CONVERSOES


TRUNCATE TABLE OPERADORES
INSERT INTO OPERADORES
SELECT * FROM [BALCAO].LOJA.DBO.OPERADORES

TRUNCATE TABLE PRODUTOS
INSERT INTO PRODUTOS
SELECT * FROM [BALCAO].LOJA.DBO.PRODUTOS


TRUNCATE TABLE PRODUTOS_COMPOSICOES
INSERT INTO PRODUTOS_COMPOSICOES
SELECT * FROM [BALCAO].LOJA.DBO.PRODUTOS_COMPOSICOES


TRUNCATE TABLE REGRAS_GERAR_VALES_PRESENTES_PDV
INSERT INTO REGRAS_GERAR_VALES_PRESENTES_PDV
SELECT * FROM [BALCAO].LOJA.DBO.REGRAS_GERAR_VALES_PRESENTES_PDV


TRUNCATE TABLE REGRAS_GERAR_VALES_PRESENTES_PDV_GRUPOS
INSERT INTO REGRAS_GERAR_VALES_PRESENTES_PDV_GRUPOS
SELECT * FROM [BALCAO].LOJA.DBO.REGRAS_GERAR_VALES_PRESENTES_PDV_GRUPOS


TRUNCATE TABLE REGRAS_GERAR_VALES_PRESENTES_PDV_PRODUTOS
INSERT INTO REGRAS_GERAR_VALES_PRESENTES_PDV_PRODUTOS
SELECT * FROM [BALCAO].LOJA.DBO.REGRAS_GERAR_VALES_PRESENTES_PDV_PRODUTOS


TRUNCATE TABLE REGRAS_GERAR_VALES_PRESENTES_PDV_SECOES
INSERT INTO REGRAS_GERAR_VALES_PRESENTES_PDV_SECOES
SELECT * FROM [BALCAO].LOJA.DBO.REGRAS_GERAR_VALES_PRESENTES_PDV_SECOES


TRUNCATE TABLE REGRAS_GERAR_VALES_PRESENTES_PDV_SUBGRUPOS
INSERT INTO REGRAS_GERAR_VALES_PRESENTES_PDV_SUBGRUPOS
SELECT * FROM [BALCAO].LOJA.DBO.REGRAS_GERAR_VALES_PRESENTES_PDV_SUBGRUPOS


TRUNCATE TABLE SERVICOS
INSERT INTO SERVICOS
SELECT * FROM [BALCAO].LOJA.DBO.SERVICOS


TRUNCATE TABLE SUBSTITUTOS
INSERT INTO SUBSTITUTOS
SELECT * FROM [BALCAO].LOJA.DBO.SUBSTITUTOS


TRUNCATE TABLE TABELA_VALORES_RECARGAS
INSERT INTO TABELA_VALORES_RECARGAS
SELECT * FROM [BALCAO].LOJA.DBO.TABELA_VALORES_RECARGAS


TRUNCATE TABLE TABELAS_DESCONTOS
INSERT INTO TABELAS_DESCONTOS
SELECT * FROM [BALCAO].LOJA.DBO.TABELAS_DESCONTOS


TRUNCATE TABLE TABELAS_ENCARTES
INSERT INTO TABELAS_ENCARTES
SELECT * FROM [BALCAO].LOJA.DBO.TABELAS_ENCARTES


TRUNCATE TABLE TAMANHOS_PRODUTOS
INSERT INTO TAMANHOS_PRODUTOS
SELECT * FROM [BALCAO].LOJA.DBO.TAMANHOS_PRODUTOS


TRUNCATE TABLE TIPOS_CANCELAMENTOS
INSERT INTO TIPOS_CANCELAMENTOS
SELECT * FROM [BALCAO].LOJA.DBO.TIPOS_CANCELAMENTOS


TRUNCATE TABLE TIPOS_SANGRIAS
INSERT INTO TIPOS_SANGRIAS
SELECT * FROM [BALCAO].LOJA.DBO.TIPOS_SANGRIAS


TRUNCATE TABLE TIPOS_TOTALIZADORES_NT
INSERT INTO TIPOS_TOTALIZADORES_NT
SELECT * FROM [BALCAO].LOJA.DBO.TIPOS_TOTALIZADORES_NT